### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by LexsaTV** [h4x4d/HearthstoneDeckView#1]
Как правильно получить или ввести токен blizzard?
В Api создал приложение, получил Client ID и Client Secret, так же запросом через консоль получил access_token но все они выдают ошибку

**Comment by hextract** [comment]
Blizzard обновили свое API. Бот работает на старом методе генерации токенов. Постараюсь переписать, как найду несколько свободных часов.

**Comment by hextract** [comment]
Upd: все оказалось очень тривиально

Пофикшено
